### ISSUE TITLE
Add Mend (formerly known as Whitesource) Scan

### ISSUE THREAD

**Issue by coliff** [trimble-oss/modus-icons#130]
Add this to `.github/workflows/whitesource-scan.yml`

```yml
nes (21 sloc)  517 Bytes

name: WhiteSource Scan

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scan:
    name: WhiteSource Scan Runner
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run WhiteSource Scan Action
        uses: trimble-oss/gh-actions/mend-scanner@main

        with:
          apiKey: ${{ secrets.WSS_API_KEY }}
          configFile: "wss-unified-agent.config"
```
