### ISSUE TITLE
Publish npm package to @trimble-oss GitHub registry as well

### ISSUE THREAD

**Issue by ryan-henness-trimble** [trimble-oss/modus-icons#192]
## Issue
Our team uses private packages under the @trimble-oss organization that are hosted on the GitHub registry. Since we've got to point npm to this registry manually, we cannot mix and match the @trimble-oss scope with packages that are on the npm registry. That means if we're using our private packages then we're not able to pull in the icon package from the npm public registry as well

## Suggested Fix
Publish the npm package to both the npm and GitHub registry. Here is an example of how we're publishing to both registries with the Modus Web Components: https://github.com/trimble-oss/modus-web-components/blob/main/.github/workflows/publish.yml

**Comment by coliff** [comment]
I think we can do this then. It should be simple enough to setup by adding these steps to the bottom of the `publish-to-npm` workflow.

```yml
      - name: Set GitHub Registry Auth Token
        run: npm set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}

      - name: Publish npm Package to GitHub Registry
        run: npm publish --access public --ignore-scripts --@trimble-oss:registry='https://npm.pkg.github.com'
```        

I'll make a PR and request you for review.
